# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confederacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('confederacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selecciones.Confederacion')),
            ],
        ),
        migrations.AddField(
            model_name='jugador',
            name='seleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selecciones.Seleccion'),
        ),
    ]
